### ISSUE TITLE
bugs stickers: the forward-message not displayed on jabber side

### ISSUE THREAD

**Issue by jt3k** [jt3k/chat-linker#45]
if you forward a message with a sticker then it is not visible on the jabber side

in console i see
```
  TypeError: Cannot read property 'replace' of undefined
      at ForwardedMessage.toString (/Users/jt3k/tmp/chat-linker/bots/telegram/client.js:74:29)
      at prepareMessage (/Users/jt3k/tmp/chat-linker/bots/telegram/client.js:123:33)
      at prepareEmittingMessageDetails (/Users/jt3k/tmp/chat-linker/bots/telegram/client.js:135:15)
      at client.on (/Users/jt3k/tmp/chat-linker/bots/telegram/client.js:149:15)
      at Promise.resolve.then (/Users/jt3k/tmp/chat-linker/node_modules/telegraf/lib/core/composer.js:81:56)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by jt3k** [comment]
fixed in PR #47
