### ISSUE TITLE
Followed instructions but can't run

### ISSUE THREAD

**Issue by lisbonjoker** [jt3k/chat-linker#86]
```
> chat-linker@1.0.0 dev /home/artur/chat-linker
> cross-env NODE_ENV=dev node --inspect dist/app.js

Debugger listening on ws://127.0.0.1:9229/4a43126a-1307-419e-be0b-ad24ddb37d82
For help, see: https://nodejs.org/en/docs/inspector
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../../../app-config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/joker/chat-linker/dist/bots/jabber/index.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chat-linker@1.0.0 dev: `cross-env NODE_ENV=dev node --inspect dist/app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chat-linker@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/artur/.npm/_logs/2021-07-10T00_40_02_145Z-debug.log

```

**Comment by lisbonjoker** [comment]
I had a misspelled when renaming, didn't notice
